import { BookOpenCheck, BriefcaseBusiness, Check, CircleUserRound, FileUser, GraduationCap, MapPin, Pencil, Sparkles, Target, TrendingUp } from "lucide-react";
import { profileMilestones, trainingHistory, userProfile } from "@/src/data/userProfile";
import { PageIntro, ProgressBar, SectionCard, StatusBadge, primaryButton, secondaryButton } from "@/src/components/dashboard/ui-v2";

export default function ProfilePage() { return <div className="space-y-5 sm:space-y-6"><PageIntro eyebrow="Profil personal" title="Semakin lengkap profilmu, semakin tajam rekomendasi NexWork" description="Gunakan data yang benar-benar mencerminkan minat, kemampuan, dan wilayahmu. Untuk MVP, seluruh data di halaman ini adalah simulasi." action={<button className={primaryButton}><Pencil size={15} /> Edit profil</button>} />
  <div className="grid gap-5 xl:grid-cols-12"><section className="dashboard-card relative overflow-hidden p-6 xl:col-span-4"><div className="absolute inset-x-0 top-0 h-24 bg-gradient-to-r from-[#061A33] to-[#0B4EA2]" /><div className="relative mt-9 flex flex-col items-center text-center"><span className="flex h-24 w-24 items-center justify-center rounded-[28px] bg-[#FFD43B] text-2xl font-bold text-[#061A33] shadow-[0_12px_30px_rgba(6,26,51,.18)]">{userProfile.initials}</span><h2 className="mt-4 text-xl font-bold text-[#061A33]">{userProfile.name}</h2><StatusBadge value={userProfile.status} /><p className="mt-3 flex items-center gap-1.5 text-xs text-[#718298]"><MapPin size={13} />{userProfile.location}</p><div className="mt-6 w-full rounded-2xl bg-[#F2F6FA] p-4 text-left"><div className="flex items-center justify-between"><p className="text-xs font-bold text-[#344B64]">Kelengkapan profil</p><p className="text-xs font-bold text-[#0B4EA2]">{userProfile.profileProgress}%</p></div><div className="mt-3"><ProgressBar value={userProfile.profileProgress} /></div></div><div className="mt-4 grid w-full grid-cols-3 gap-2">{[[userProfile.completedTrainings,"Pelatihan"],[userProfile.learningHours,"Jam belajar"],[userProfile.applications,"Lamaran"]].map(([v,l]) => <div key={l} className="rounded-xl bg-[#F7F9FC] p-3"><p className="text-lg font-bold text-[#061A33]">{v}</p><p className="text-[9px] text-[#8291A3]">{l}</p></div>)}</div></div></section>
  <div className="space-y-5 xl:col-span-8"><SectionCard title="Arah karier & skill utama" description="Digunakan untuk menyusun rekomendasi lowongan dan pelatihan."><div className="grid gap-5 md:grid-cols-2"><div><p className="text-[10px] font-bold uppercase tracking-[.1em] text-[#8291A3]">Minat karier</p><div className="mt-3 flex flex-wrap gap-2">{userProfile.careerInterests.map(x => <span key={x} className="rounded-full bg-[#061A33] px-3 py-1.5 text-[11px] font-bold text-white">{x}</span>)}</div></div><div><p className="text-[10px] font-bold uppercase tracking-[.1em] text-[#8291A3]">Skill utama</p><div className="mt-3 flex flex-wrap gap-2">{userProfile.primarySkills.map(x => <span key={x} className="rounded-full bg-[#EAF3FC] px-3 py-1.5 text-[11px] font-bold text-[#20517F]">{x}</span>)}</div></div></div><div className="mt-6 grid gap-3 md:grid-cols-2"><div className="rounded-xl bg-[#FFF6D4] p-4"><p className="text-[10px] font-bold uppercase text-[#755900]">Kesiapan kerja</p><p className="mt-2 text-3xl font-bold text-[#061A33]">{userProfile.readiness}%</p><div className="mt-3"><ProgressBar value={userProfile.readiness} tone="yellow" /></div></div><div className="rounded-xl bg-[#EAF3FC] p-4"><p className="text-[10px] font-bold uppercase text-[#0B4EA2]">Saran personal</p><p className="mt-2 text-xs leading-5 text-[#365878]">Tambahkan project data yang menjelaskan masalah, proses, dan hasil agar profilmu lebih kuat.</p></div></div></SectionCard>
  <SectionCard title="Progress perkembangan diri" description="Lima bagian yang membentuk kualitas rekomendasi."><div className="grid gap-3 sm:grid-cols-2">{profileMilestones.map(item => <div key={item.label} className="flex items-center gap-3 rounded-xl bg-[#F3F6FA] p-3"><span className={`flex h-7 w-7 items-center justify-center rounded-full ${item.done ? "bg-[#17A77B] text-white" : "bg-white text-[#9AA8B7]"}`}>{item.done ? <Check size={14} /> : null}</span><p className="text-xs font-semibold text-[#3D536B]">{item.label}</p></div>)}</div></SectionCard></div></div>
  <SectionCard title="Riwayat pelatihan" description="Sertifikat dan hasil belajar yang terhubung ke profilmu." action={<button className={secondaryButton}>Lihat semua</button>}><div className="table-scroll"><table className="min-w-[720px] w-full text-left text-xs"><thead><tr className="text-[10px] uppercase tracking-[.08em] text-[#8392A3]"><th className="pb-3 font-bold">Pelatihan</th><th className="pb-3 font-bold">Selesai</th><th className="pb-3 font-bold">Nilai</th><th className="pb-3 font-bold">Status</th></tr></thead><tbody>{trainingHistory.map(item => <tr key={item.name} className="border-t border-[#EAF0F5]"><td className="py-4 font-bold text-[#183653]">{item.name}</td><td className="py-4 text-[#64778D]">{item.date}</td><td className="py-4 font-bold text-[#061A33]">{item.score}</td><td className="py-4"><StatusBadge value={item.result} /></td></tr>)}</tbody></table></div></SectionCard>
  </div>; }
