import { Award, Check, CircleDot, Sparkles, Target, TrendingUp } from "lucide-react";
import { achievementBadges, progressTargets, readinessMetrics } from "@/src/data/selfProgress";
import { PageIntro, ProgressBar, SectionCard, StatCard, primaryButton } from "@/src/components/dashboard/ui-v2";
import { ReadinessRadar, WeeklyProgressChart } from "@/src/components/dashboard/progress-charts";

export default function SelfProgressPage() { return <div className="space-y-5 sm:space-y-6"><PageIntro eyebrow="Career readiness" title="Kesiapanmu tumbuh saat progres kecil terus dijaga" description="Kamu sudah cukup siap untuk melamar posisi entry-level. Fokus berikutnya adalah memperkuat portofolio dan latihan interview." action={<div className="rounded-xl bg-white/10 px-5 py-3"><p className="text-[10px] text-[#BFD8FA]">Skor saat ini</p><p className="text-2xl font-bold text-[#FFD43B]">72%</p></div>} />
  <div className="grid auto-rows-fr gap-4 sm:grid-cols-2 xl:grid-cols-3">{readinessMetrics.map((item,i) => <StatCard key={item.label} title={item.label} value={`${item.value}%`} note={item.value >= 75 ? "Sudah kuat untuk level awal." : item.value >= 60 ? "Terus naik, jaga konsistensi." : "Prioritas utama bulan ini."} icon={[TrendingUp, CircleDot, Award][i%3]} tone={item.value < 60 ? "amber" : item.value > 78 ? "green" : "blue"} />)}</div>
  <div className="grid gap-5 xl:grid-cols-2"><SectionCard title="Peta kesiapan karier" description="Perbandingan enam indikator utama."><ReadinessRadar /></SectionCard><SectionCard title="Perkembangan enam minggu" description="Skormu naik 20 poin sejak mulai menggunakan NexWork."><WeeklyProgressChart /></SectionCard></div>
  <div className="grid gap-5 xl:grid-cols-12"><SectionCard className="xl:col-span-8" title="Target yang sedang dikerjakan" description="Urutan dibuat berdasarkan dampaknya terhadap peluang kerja."><div className="space-y-4">{progressTargets.map(target => <div key={target.title} className="rounded-xl bg-[#F3F6FA] p-4"><div className="mb-3 flex items-center justify-between gap-4"><div className="flex items-center gap-3"><span className={`flex h-8 w-8 items-center justify-center rounded-xl ${target.progress === 100 ? "bg-[#17A77B] text-white" : "bg-white text-[#0B4EA2]"}`}>{target.progress === 100 ? <Check size={16} /> : <Target size={16} />}</span><p className="text-xs font-bold text-[#263E59]">{target.title}</p></div><span className="text-[10px] font-semibold text-[#77889B]">{target.due}</span></div><ProgressBar value={target.progress} tone={target.progress === 100 ? "green" : "blue"} /></div>)}</div></SectionCard><SectionCard className="xl:col-span-4" title="Badge pencapaian" description="Bukti kecil dari kebiasaan yang sudah kamu bangun."><div className="grid grid-cols-2 gap-3">{achievementBadges.map((badge,i) => <div key={badge} className={`flex min-h-[110px] flex-col items-center justify-center rounded-2xl p-3 text-center ${i===0 ? "bg-[#061A33] text-white" : "bg-[#F1F6FB] text-[#24415F]"}`}><Award className={i===0 ? "text-[#FFD43B]" : "text-[#0B4EA2]"} size={23} /><p className="mt-2 text-[11px] font-bold leading-4">{badge}</p></div>)}</div><button className={`${primaryButton} mt-5 w-full`}><Sparkles size={14} /> Lihat rekomendasi otomatis</button></SectionCard></div>
  </div>; }
