import Link from "next/link";
import { ArrowRight, BookOpenCheck, BriefcaseBusiness, BusFront, FileUser, TrendingUp } from "lucide-react";
import { IndonesiaMap } from "@/src/components/dashboard/indonesia-map";

export function LandingDashboardPreview() {
  return <section id="dashboard-preview" className="scroll-mt-24 bg-[#061A33] py-20 text-white"><div className="mx-auto max-w-[1320px] px-4 sm:px-6 lg:px-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#FFD23F]">Dashboard preview</p><h2 className="mt-3 max-w-2xl text-3xl font-bold tracking-[-.035em] sm:text-4xl">Command center nasional, tetap relevan untuk perjalanan karier personal.</h2></div><Link href="/login" className="inline-flex w-fit items-center gap-2 rounded-xl bg-[#FFD23F] px-5 py-3 text-xs font-bold text-[#061A33]">Buka dashboard demo <ArrowRight size={15} /></Link></div>
    <div className="mt-9 rounded-[26px] bg-white/[.07] p-3 shadow-[inset_0_1px_0_rgba(255,255,255,.1),0_30px_80px_rgba(0,0,0,.2)] sm:p-5"><div className="grid gap-4 xl:grid-cols-12"><div className="xl:col-span-8"><IndonesiaMap compact /></div><div className="grid grid-cols-2 gap-3 xl:col-span-4">{[[TrendingUp,"Career readiness","72%"],[BriefcaseBusiness,"Job match","92%"],[FileUser,"CV ready","78%"],[BookOpenCheck,"Pelatihan","6 kelas"]].map(([Icon,label,value]) => { const ItemIcon=Icon as typeof TrendingUp; return <div key={label as string} className="rounded-2xl bg-[#0A315C] p-4"><ItemIcon className="text-[#FFD23F]" size={18} /><p className="mt-4 text-[9px] text-[#9FC2E4]">{label as string}</p><p className="mt-1 text-lg font-bold">{value as string}</p></div>; })}</div></div>
      <div className="mt-4 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-[#0A315C] p-4"><p className="text-[9px] font-bold uppercase tracking-[.12em] text-[#7EB9F2]">Peluang terbaik</p><p className="mt-3 text-sm font-bold">Junior Data Analyst</p><p className="mt-1 text-[10px] text-[#A8C5E2]">Surabaya · 92% cocok</p></div><div className="rounded-2xl bg-[#0A315C] p-4"><p className="text-[9px] font-bold uppercase tracking-[.12em] text-[#7EB9F2]">Pelatihan berikutnya</p><p className="mt-3 text-sm font-bold">Dasar Data Analysis</p><p className="mt-1 text-[10px] text-[#A8C5E2]">Hybrid · Pertemuan 3</p></div><div className="flex items-center gap-3 rounded-2xl bg-[#0B4EA2] p-4"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#FFD23F] text-[#061A33]"><BusFront size={21} /></span><div><p className="text-[9px] text-[#B9D7F3]">BLK Mobile terdekat</p><p className="mt-1 text-sm font-bold">18 km · 4 program</p></div></div></div>
    </div></div></section>;
}
