import Link from "next/link";
import { ArrowRight, BadgeCheck, BookOpenCheck, BriefcaseBusiness, BusFront, Check, FileUser, Handshake, MapPinned, Menu, Sparkles, Target, TrendingUp } from "lucide-react";
import { LandingHybridHero } from "@/src/components/landing-hybrid-hero";
import { FeatureShowcase } from "@/src/components/feature-showcase";
import { IndonesiaMap } from "@/src/components/dashboard/indonesia-map";
import { LandingDashboardPreview } from "@/src/components/landing-dashboard-preview";

const steps = ["Lengkapi profil dan minat karier", "Dapatkan rekomendasi pelatihan dan kerja", "Bangun CV serta portofolio digital", "Pantau progres sampai siap melamar"];

export function LandingV3() {
  return <main className="min-h-screen overflow-hidden bg-[#F8FAFC] text-[#102033]">
    <header className="sticky top-0 z-40 border-b border-[#DCE7F1]/80 bg-white/92 backdrop-blur-xl"><nav className="mx-auto flex min-h-[74px] max-w-[1320px] items-center justify-between px-4 sm:px-6 lg:px-8"><Link href="#beranda" className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-[14px] bg-[#061A33] text-[#FFD23F]"><Sparkles size={20} /></span><span><b className="block text-[15px] text-[#061A33]">NexWork 2045</b><small className="block text-[9px] font-bold uppercase tracking-[.14em] text-[#0B4EA2]">Workforce Intelligence</small></span></Link><div className="hidden items-center gap-7 text-xs font-bold text-[#52667F] lg:flex"><a href="#masalah" className="transition hover:text-[#0B4EA2]">Masalah</a><a href="#solusi" className="transition hover:text-[#0B4EA2]">Solusi</a><a href="#blk-mobile" className="transition hover:text-[#0B4EA2]">BLK Mobile</a><a href="#dashboard-preview" className="transition hover:text-[#0B4EA2]">Dashboard</a><Link href="/login" className="transition hover:text-[#0B4EA2]">Demo</Link></div><Link href="/login" className="hidden rounded-xl bg-[#061A33] px-5 py-3 text-xs font-bold text-white shadow-lg shadow-[#061A33]/15 transition hover:bg-[#0B4EA2] lg:inline-flex">Masuk Demo</Link><Link href="/login" className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#EAF3FC] text-[#061A33] lg:hidden" aria-label="Masuk demo"><Menu size={18} /></Link></nav></header>

    <LandingHybridHero />

    <section className="relative z-20 mx-auto -mt-12 max-w-[1240px] px-4 sm:px-6 lg:px-8"><div className="grid gap-3 rounded-[22px] bg-white p-3 shadow-[0_20px_55px_rgba(6,26,51,.14)] sm:grid-cols-2 lg:grid-cols-4">{[[BriefcaseBusiness,"Cari Kerja Cerdas","Lowongan dengan match score","/login"],[BookOpenCheck,"Daftar Pelatihan","Online, hybrid, dan mobile","/login"],[FileUser,"CV & Portofolio","Dokumen karier siap pakai","/login"],[TrendingUp,"Progress Kesiapan","Targetmu selalu terukur","/login"]].map(([Icon,title,copy,href]) => { const ItemIcon=Icon as typeof BriefcaseBusiness; return <Link key={title as string} href={href as string} className="group flex min-h-[76px] items-center gap-3 rounded-2xl bg-[#F5F8FC] p-3 transition hover:-translate-y-0.5 hover:bg-[#EAF3FC]"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-white text-[#0B4EA2] shadow-sm transition group-hover:bg-[#FFD23F] group-hover:text-[#061A33]"><ItemIcon size={18} /></span><span><b className="block text-xs text-[#061A33]">{title as string}</b><small className="mt-1 block text-[10px] text-[#718298]">{copy as string}</small></span></Link>; })}</div></section>

    <section id="masalah" className="scroll-mt-24 px-4 py-20 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-[1320px] gap-8 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#0B4EA2]">Masalah yang dibaca</p><h2 className="mt-3 text-3xl font-bold tracking-[-.035em] text-[#061A33] sm:text-4xl">Bonus demografi tidak cukup hanya dibaca dari jumlah tenaga kerja.</h2><p className="mt-4 text-sm leading-7 text-[#64788E]">Yang perlu dijembatani adalah jarak antara skill lulusan, kebutuhan industri, dan akses pelatihan yang berbeda di setiap wilayah.</p></div><div className="grid gap-3 sm:grid-cols-3">{[["01","Data belum menjadi arah","Informasi pendidikan dan industri perlu dibaca sebagai keputusan."],["02","Skill berbeda tiap wilayah","Kebutuhan Cilegon tidak sama dengan Garut atau Lombok Timur."],["03","Pelatihan perlu tepat sasaran","Program harus terhubung dengan peluang kerja dan kesiapan peserta."]].map(([number,title,copy]) => <article key={number} className="dashboard-card flex min-h-[190px] flex-col p-5"><span className="text-xs font-bold text-[#0B4EA2]">{number}</span><h3 className="mt-5 text-sm font-bold text-[#061A33]">{title}</h3><p className="mt-2 text-xs leading-5 text-[#667A90]">{copy}</p><span className="mt-auto h-1 w-10 rounded-full bg-[#FFD23F]" /></article>)}</div></div></section>

    <FeatureShowcase />

    <section id="cara-kerja" className="scroll-mt-24 bg-[#061A33] py-20 text-white"><div className="mx-auto max-w-[1320px] px-4 sm:px-6 lg:px-8"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#FFD23F]">Cara kerjanya</p><h2 className="mt-3 max-w-2xl text-3xl font-bold tracking-[-.035em] sm:text-4xl">Dari profil diri ke peluang kerja yang tepat.</h2><div className="mt-10 grid gap-3 md:grid-cols-2 lg:grid-cols-4">{steps.map((step,index) => <article key={step} className="relative rounded-2xl bg-white/[.065] p-5 shadow-[inset_0_1px_0_rgba(255,255,255,.08)]"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#FFD23F] text-sm font-bold text-[#061A33]">{index+1}</span><p className="mt-4 text-xs font-bold leading-5">{step}</p>{index<steps.length-1?<span className="absolute -right-2 top-8 z-10 hidden h-px w-4 bg-[#FFD23F]/70 lg:block" />:null}</article>)}</div></div></section>

    <section className="px-4 py-20 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-[1320px] gap-8 lg:grid-cols-[1.35fr_.65fr]"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#0B4EA2]">Peta peluang nasional</p><h2 className="mt-3 text-3xl font-bold tracking-[-.035em] text-[#061A33] sm:text-4xl">Peluang kerja dan pelatihan berdasarkan wilayah.</h2><p className="mt-4 max-w-2xl text-sm leading-6 text-[#687B91]">Peta menggunakan geometri 38 provinsi Indonesia untuk membaca risiko, lokasi BLK Mobile, dan kebutuhan pelatihan.</p><div className="mt-7"><IndonesiaMap /></div></div><div className="flex flex-col justify-end gap-3">{[["12","Wilayah prioritas tinggi"],["28","Pelatihan aktif"],["7","BLK Mobile terjadwal"],["Digital & manufaktur","Sektor paling dibutuhkan"]].map(([value,label],index) => <div key={label} className={`rounded-2xl p-5 ${index===0?"bg-[#FFD23F]":"bg-white shadow-[0_10px_32px_rgba(6,26,51,.07)]"}`}><p className={`text-xl font-bold ${index===0?"text-[#061A33]":"text-[#0B4EA2]"}`}>{value}</p><p className="mt-1 text-xs font-semibold text-[#52667F]">{label}</p></div>)}</div></div></section>

    <LandingDashboardPreview />

    <section id="blk-mobile" className="scroll-mt-24 bg-[#EAF3FC] py-20"><div className="mx-auto grid max-w-[1320px] gap-10 px-4 sm:px-6 lg:grid-cols-[.82fr_1.18fr] lg:px-8"><div className="flex flex-col justify-center"><span className="flex h-14 w-14 items-center justify-center rounded-2xl bg-[#FFD23F] text-[#061A33]"><BusFront size={28} /></span><h2 className="mt-5 text-3xl font-bold tracking-[-.035em] text-[#061A33] sm:text-4xl">BLK Mobile: Pelatihan yang Hadir ke Wilayah Prioritas</h2><p className="mt-4 text-sm leading-7 text-[#5F748B]">BLK Mobile membantu membawa pelatihan langsung ke daerah yang membutuhkan, berdasarkan data peluang kerja dan kebutuhan skill lokal.</p><div className="mt-6 space-y-3">{["Pelatihan sesuai kebutuhan wilayah","Menjangkau daerah prioritas","Terhubung dengan peluang kerja"].map(item => <p key={item} className="flex items-center gap-2 text-xs font-bold text-[#36516C]"><span className="flex h-5 w-5 items-center justify-center rounded-full bg-white text-[#0B4EA2]"><Check size={12} /></span>{item}</p>)}</div></div><div className="rounded-[26px] bg-[#071E39] p-5 text-white shadow-[0_24px_70px_rgba(6,26,51,.2)]"><div className="grid gap-4 sm:grid-cols-[.9fr_1.1fr]"><div className="flex min-h-[230px] flex-col justify-between rounded-2xl bg-[#0B4EA2] p-5"><div className="flex items-center justify-between"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#BFD9F6]">BLK Mobile 03</p><BadgeCheck className="text-[#FFD23F]" size={20} /></div><div><BusFront className="text-[#FFD23F]" size={54} /><p className="mt-4 text-xl font-bold">Surabaya → Sidoarjo</p><p className="mt-2 text-xs text-[#C9DEF3]">Administrasi Digital · 40 peserta</p></div></div><div className="grid grid-cols-2 gap-3">{[[MapPinned,"Menjangkau daerah"],[Target,"Kebutuhan lokal"],[BadgeCheck,"Sertifikasi"],[Handshake,"Koneksi industri"]].map(([Icon,label]) => { const ItemIcon=Icon as typeof Target; return <div key={label as string} className="rounded-2xl bg-white/[.07] p-4"><ItemIcon className="text-[#FFD23F]" size={20} /><p className="mt-3 text-xs font-bold leading-5">{label as string}</p></div>; })}</div></div></div></div></section>

    <section className="mx-auto max-w-[1320px] px-4 py-20 sm:px-6 lg:px-8"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div className="flex flex-col justify-center"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#0B4EA2]">Perkembangan diri</p><h2 className="mt-3 text-3xl font-bold tracking-[-.035em] text-[#061A33] sm:text-4xl">Pantau kesiapanmu sebelum masuk dunia kerja.</h2><p className="mt-4 text-sm leading-7 text-[#687B91]">Semakin banyak pelatihan, latihan interview, dan project yang kamu selesaikan, semakin tinggi kesiapanmu untuk melamar kerja.</p></div><div className="dashboard-card grid gap-5 p-5 sm:p-7 md:grid-cols-[.7fr_1.3fr]"><div className="flex flex-col justify-center rounded-2xl bg-[#061A33] p-6 text-white"><p className="text-xs text-[#9DC4EA]">Career Readiness Score</p><p className="mt-2 text-5xl font-bold text-[#FFD23F]">72%</p><p className="mt-4 text-xs leading-5 text-[#BED5EC]">Kamu cukup siap untuk posisi entry-level.</p></div><div className="space-y-4">{[["CV Readiness",78],["Portfolio Readiness",55],["Interview Readiness",64],["Job Match Score",81]].map(([label,value],index) => <div key={label as string}><div className="mb-2 flex justify-between text-xs"><span className="font-semibold text-[#52667F]">{label as string}</span><b>{value}%</b></div><div className="h-2 rounded-full bg-[#E8EDF3]"><div className={`h-full rounded-full ${index===1?"bg-[#FFD23F]":"bg-[#0B4EA2]"}`} style={{width:`${value}%`}} /></div></div>)}</div></div></div></section>

    <section className="px-4 pb-20 sm:px-6 lg:px-8"><div className="relative mx-auto max-w-[1320px] overflow-hidden rounded-[28px] bg-[#0B4EA2] px-6 py-12 text-center text-white shadow-[0_24px_70px_rgba(11,78,162,.24)] sm:px-10"><div className="absolute inset-0 nexwork-dot-map opacity-25" /><div className="relative"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#FFD23F]">Mulai dari langkah kecil</p><h2 className="mx-auto mt-3 max-w-2xl text-3xl font-bold tracking-[-.035em] sm:text-4xl">Siap mulai perjalanan karirmu?</h2><p className="mx-auto mt-4 max-w-2xl text-sm leading-6 text-[#D4E5F7]">Coba demo NexWork 2045 dan lihat bagaimana pelatihan, CV digital, peluang kerja, dan BLK Mobile terhubung dalam satu platform.</p><Link href="/login" className="mt-7 inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[#FFD23F] px-6 text-sm font-bold text-[#061A33]">Masuk Demo <ArrowRight size={16} /></Link></div></div></section>

    <footer className="border-t border-[#DCE7F1] bg-white"><div className="mx-auto flex max-w-[1320px] flex-col gap-3 px-4 py-8 text-xs text-[#718298] sm:flex-row sm:items-center sm:justify-between sm:px-6 lg:px-8"><p><b className="text-[#061A33]">NexWork 2045</b> · Workforce intelligence untuk pelatihan tepat sasaran.</p><p>Prototype berbasis data simulasi</p></div></footer>
  </main>;
}
