import Link from "next/link";
import { ArrowRight, BarChart3, BriefcaseBusiness, BusFront, FileUser, GraduationCap, MapPinned, Navigation, Search, ShieldAlert } from "lucide-react";

export function LandingHybridHero() {
  return <section id="beranda" className="relative overflow-hidden bg-[radial-gradient(circle_at_78%_35%,rgba(30,136,229,.22),transparent_28%),linear-gradient(135deg,#061A33_0%,#08264A_62%,#071D38_100%)] text-white">
    <div className="absolute inset-0 nexwork-grid opacity-40" />
    <div className="absolute -right-24 top-12 h-80 w-80 rounded-full bg-[#2A8CFF]/15 blur-3xl" />
    <div className="absolute bottom-20 left-[44%] h-24 w-24 rounded-full bg-[#FFD23F]/10 blur-3xl" />
    <div className="relative mx-auto grid min-h-[calc(88vh-74px)] max-w-[1320px] items-center gap-8 px-4 pb-20 pt-12 sm:px-6 lg:grid-cols-12 lg:px-8 lg:pb-24 lg:pt-14">
      <div className="lg:col-span-5">
        <span className="inline-flex w-fit items-center gap-2 rounded-full bg-white/[.08] px-4 py-2 text-[10px] font-bold uppercase tracking-[.12em] text-[#FFD23F] shadow-[inset_0_1px_0_rgba(255,255,255,.1)]"><ShieldAlert size={14} /> Coming Soon · Demo Prototype Available</span>
        <h1 className="mt-6 max-w-xl text-4xl font-bold leading-[1.07] tracking-[-.045em] sm:text-5xl lg:text-[58px]">Memetakan <span className="text-[#FFD23F]">Risiko Kerja</span>, Mengirim Pelatihan yang <span className="text-[#FFD23F]">Tepat Sasaran.</span></h1>
        <p className="mt-6 max-w-xl text-sm leading-7 text-[#C7DBF1] sm:text-base">NexWork 2045 membaca skill mismatch di tiap wilayah, menentukan prioritas intervensi, lalu menghubungkannya dengan aksi lapangan melalui BLK Mobile.</p>
        <div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link href="/login" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[#FFD23F] px-5 text-sm font-bold text-[#061A33] shadow-[0_14px_32px_rgba(246,184,0,.2)] transition hover:-translate-y-0.5 hover:bg-[#FFDF68]">Coba Dashboard Demo <ArrowRight size={17} /></Link><a href="#cara-kerja" className="inline-flex min-h-12 items-center justify-center rounded-xl bg-white/[.09] px-5 text-sm font-bold text-white shadow-[inset_0_1px_0_rgba(255,255,255,.1)] transition hover:bg-white/[.14]">Lihat Cara Kerjanya</a></div>
        <div className="mt-9 grid grid-cols-3 gap-3">{[["38","indikator wilayah"],["6","fitur utama"],["2045","arah bonus demografi"]].map(([value,label]) => <div key={label} className="border-l-2 border-[#FFD23F] pl-3"><p className="text-xl font-bold text-[#FFD23F] sm:text-2xl">{value}</p><p className="mt-1 text-[9px] leading-4 text-[#9DBDDE] sm:text-[10px]">{label}</p></div>)}</div>
      </div>

      <div className="relative mx-auto h-[540px] w-full max-w-[680px] lg:col-span-7">
        <div className="absolute inset-4 rounded-[36px] bg-gradient-to-br from-white/[.075] to-white/[.025] shadow-[inset_0_1px_0_rgba(255,255,255,.1),0_32px_80px_rgba(0,0,0,.2)] backdrop-blur-sm" />
        <div className="absolute left-3 top-72 h-2 w-2 rounded-full bg-[#FFD23F] shadow-[0_0_0_8px_rgba(255,210,63,.12)]" />

        <div className="absolute left-5 top-20 hidden w-[370px] rounded-[24px] bg-[#0A315C]/95 p-5 shadow-[0_25px_65px_rgba(0,0,0,.26)] ring-1 ring-white/10 sm:block">
          <div className="flex items-center justify-between"><div><p className="text-[9px] font-bold uppercase tracking-[.14em] text-[#79B9FA]">Dashboard Pribadi</p><p className="mt-1 text-base font-bold">Career readiness</p></div><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-white/[.08] text-[#FFD23F]"><BarChart3 size={19} /></span></div>
          <div className="mt-5 flex items-end justify-between"><p className="text-4xl font-bold text-[#FFD23F]">72%</p><p className="text-[9px] font-semibold text-[#9CC2E8]">+5 poin bulan ini</p></div><div className="mt-3 h-2 rounded-full bg-white/10"><div className="h-full w-[72%] rounded-full bg-[#2A8CFF]" /></div>
          <div className="mt-5 grid grid-cols-4 gap-2">{[["Job match","92%"],["CV ready","78%"],["Pelatihan","6"],["Lamaran","8"]].map(([label,value]) => <div key={label} className="rounded-xl bg-white/[.065] p-2.5"><p className="text-[8px] leading-3 text-[#94B8DA]">{label}</p><p className="mt-1 text-xs font-bold">{value}</p></div>)}</div>
        </div>

        <div className="absolute left-1/2 top-4 z-20 w-[232px] -translate-x-[5%] rounded-[34px] bg-[#041327] p-2.5 shadow-[0_32px_80px_rgba(0,0,0,.4)] sm:left-auto sm:right-8 sm:translate-x-0">
          <div className="overflow-hidden rounded-[27px] bg-white"><div className="flex justify-center bg-[#041327] pb-2"><span className="h-5 w-24 rounded-b-xl bg-black" /></div><div className="p-4 text-[#102033]"><p className="text-[9px] font-bold text-[#0B4EA2]">Halo, Ilham 👋</p><h3 className="mt-1 text-[15px] font-bold leading-5 text-[#061A33]">Siap jadi bagian dari generasi 2045?</h3><div className="mt-4 rounded-xl bg-[#EAF3FC] p-3"><div className="flex items-center gap-2"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#0B4EA2] text-[#FFD23F]"><BriefcaseBusiness size={15} /></span><div><p className="text-[8px] text-[#718298]">Rekomendasi untukmu</p><p className="text-[10px] font-bold text-[#061A33]">Junior Data Analyst</p></div></div><div className="mt-3 flex items-center justify-between"><span className="text-[8px] text-[#52667F]">Surabaya</span><span className="rounded-full bg-[#DDF7ED] px-2 py-1 text-[8px] font-bold text-[#087356]">92% cocok</span></div></div><p className="mt-4 text-[8px] font-bold uppercase tracking-[.1em] text-[#7A8A9D]">Mulai dari sini</p><div className="mt-2 grid grid-cols-4 gap-1.5">{[[Search,"Kerja"],[GraduationCap,"Latihan"],[MapPinned,"Peluang"],[FileUser,"CV"]].map(([Icon,label]) => { const ItemIcon = Icon as typeof Search; return <div key={label as string} className="text-center"><span className="mx-auto flex h-8 w-8 items-center justify-center rounded-lg bg-[#F1F5F9] text-[#0B4EA2]"><ItemIcon size={14} /></span><p className="mt-1 text-[6px] font-semibold text-[#52667F]">{label as string}</p></div>; })}</div><div className="mt-4 h-20 rounded-xl bg-[#061A33] p-3"><p className="text-[7px] text-[#93B9DF]">Peta peluang kerja</p><div className="mt-2 flex h-9 items-end gap-1">{[25,34,28,42,36,48,41].map((height,index)=><span key={index} className={`flex-1 rounded-t-sm ${index===5?"bg-[#FFD23F]":"bg-[#2A8CFF]"}`} style={{height}} />)}</div></div></div></div>
        </div>

        <div className="absolute bottom-12 right-5 z-30 w-[300px] rounded-[22px] bg-white/[.96] p-3.5 text-[#102033] shadow-[0_24px_65px_rgba(0,0,0,.3)] sm:right-0"><div className="rounded-2xl bg-[#0B4EA2] p-4 text-white"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#FFD23F] text-[#061A33]"><BusFront size={23} /></span><div><p className="text-[8px] font-bold uppercase tracking-[.12em] text-[#BCD9F5]">Pelatihan Keliling</p><p className="mt-1 text-sm font-bold">BLK Mobile</p></div></div><div className="mt-3 flex items-center gap-2 text-[8px] font-semibold text-[#E3F0FC]"><Navigation className="text-[#FFD23F]" size={12} />Surabaya → Sidoarjo → Gresik</div></div></div>

        <span className="absolute left-1 top-5 z-30 hidden rounded-xl bg-white px-3 py-2 text-[9px] font-bold text-[#16466F] shadow-xl lg:block">Cari Kerja Cerdas</span><span className="absolute right-0 top-1/3 z-30 hidden rounded-xl bg-[#FFD23F] px-3 py-2 text-[9px] font-bold text-[#061A33] shadow-xl lg:block">Pelatihan Terarah</span><span className="absolute bottom-5 left-1/3 z-30 hidden rounded-xl bg-white px-3 py-2 text-[9px] font-bold text-[#16466F] shadow-xl lg:block">CV Digital</span>
      </div>
    </div>
  </section>;
}
