import Link from "next/link";
import { ArrowRight, BadgeCheck, BarChart3, BookOpenCheck, BriefcaseBusiness, BusFront, Check, CircleUserRound, FileUser, GraduationCap, Handshake, MapPinned, Menu, MessageCircleMore, Navigation, Search, Sparkles, Target, TrendingUp } from "lucide-react";
import { IndonesiaMap } from "@/src/components/dashboard/indonesia-map";
import { FeatureShowcase } from "@/src/components/feature-showcase";
import { LandingHybridHero } from "@/src/components/landing-hybrid-hero";
import { LandingDashboardPreview } from "@/src/components/landing-dashboard-preview";

const features = [
  [BriefcaseBusiness,"Cari Kerja Cerdas","Rekomendasi lowongan berdasarkan skill, minat, dan lokasi."],
  [BookOpenCheck,"Daftar Pelatihan","Pilih kelas online, hybrid, atau BLK Mobile sesuai kebutuhan industri."],
  [MapPinned,"Peta Peluang Kerja","Baca peluang kerja dan kebutuhan skill di 38 provinsi."],
  [FileUser,"CV & Portofolio Digital","Bangun CV, sertifikat, dan project dalam satu profil karier."],
  [MessageCircleMore,"Konsultasi Karir","Dapatkan arahan untuk interview, CV, dan pilihan jalur karier."],
  [TrendingUp,"Progress Kesiapan Kerja","Pantau perkembangan skill dan kesiapanmu untuk melamar."],
  [Handshake,"Koneksi Industri","Terhubung dengan perusahaan, UMKM, dan mitra pelatihan."],
  [BusFront,"BLK Mobile","Pelatihan keliling yang hadir lebih dekat ke wilayah prioritas."],
];

const steps = ["Lengkapi profil dan minat karier","Dapatkan rekomendasi pelatihan dan kerja","Bangun CV serta portofolio digital","Pantau progres sampai siap melamar"];

export function LandingV2() {
  return <main className="min-h-screen overflow-hidden bg-[#F8FAFC] text-[#102033]">
    <header className="sticky top-0 z-40 border-b border-[#DCE7F1]/80 bg-white/92 backdrop-blur-xl"><nav className="mx-auto flex min-h-[74px] max-w-[1320px] items-center justify-between px-4 sm:px-6 lg:px-8"><Link href="#beranda" className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-[14px] bg-[#061A33] text-[#FFD23F]"><Sparkles size={20} /></span><span><b className="block text-[15px] text-[#061A33]">NexWork 2045</b><small className="block text-[9px] font-bold uppercase tracking-[.14em] text-[#0B4EA2]">Workforce Intelligence</small></span></Link><div className="hidden items-center gap-7 text-xs font-bold text-[#52667F] lg:flex"><a href="#masalah" className="transition hover:text-[#0B4EA2]">Masalah</a><a href="#solusi" className="transition hover:text-[#0B4EA2]">Solusi</a><a href="#blk-mobile" className="transition hover:text-[#0B4EA2]">BLK Mobile</a><a href="#dashboard-preview" className="transition hover:text-[#0B4EA2]">Dashboard</a><Link href="/login" className="transition hover:text-[#0B4EA2]">Demo</Link></div><Link href="/login" className="hidden rounded-xl bg-[#061A33] px-5 py-3 text-xs font-bold text-white shadow-lg shadow-[#061A33]/15 transition hover:bg-[#0B4EA2] lg:inline-flex">Masuk Demo</Link><Link href="/login" className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#EAF3FC] text-[#061A33] lg:hidden" aria-label="Masuk demo"><Menu size={18} /></Link></nav></header>

    <LandingHybridHero />

    <section id="legacy-beranda" className="hidden"><div className="absolute inset-0 nexwork-dot-map opacity-25 [mask-image:linear-gradient(90deg,transparent_28%,black_100%)]" /><div className="absolute -right-32 top-0 h-96 w-96 rounded-full bg-[#2A8CFF]/12 blur-3xl" /><div className="absolute left-[48%] top-14 h-2 w-2 rounded-full bg-[#FFD23F] shadow-[0_0_0_7px_rgba(255,210,63,.15)]" /><div className="relative mx-auto grid min-h-[calc(82vh-74px)] max-w-[1440px] gap-8 px-4 pb-24 pt-12 sm:px-6 lg:grid-cols-12 lg:px-8 lg:pb-28 lg:pt-16">
      <div className="flex flex-col justify-center lg:col-span-5"><span className="inline-flex w-fit items-center gap-2 rounded-full bg-[#FFF0A9] px-3.5 py-2 text-[10px] font-bold uppercase tracking-[.12em] text-[#715300]"><Target size={14} /> Solusi Bonus Demografi 2045</span><h1 className="mt-6 max-w-2xl text-4xl font-bold leading-[1.05] tracking-[-.045em] text-[#061A33] sm:text-5xl lg:text-[58px]">Network App untuk Generasi <span className="relative whitespace-nowrap text-[#0B4EA2]">Siap Kerja<i className="absolute -bottom-1 left-0 h-2 w-full -rotate-1 rounded-full bg-[#FFD23F] opacity-75" /></span> 2045</h1><p className="mt-6 max-w-xl text-base leading-7 text-[#52667F]">Satu aplikasi untuk mencari kerja cerdas, mengikuti pelatihan, membangun CV digital, konsultasi karier, dan terhubung dengan BLK Mobile.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link href="/login" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[#FFD23F] px-6 text-sm font-bold text-[#061A33] shadow-[0_12px_28px_rgba(246,184,0,.24)] transition hover:-translate-y-0.5 hover:bg-[#FFDE64]">Coba Demo <ArrowRight size={17} /></Link><a href="#fitur" className="inline-flex min-h-12 items-center justify-center rounded-xl bg-white px-6 text-sm font-bold text-[#061A33] shadow-[0_10px_30px_rgba(6,26,51,.1)] transition hover:-translate-y-0.5 hover:text-[#0B4EA2]">Lihat Fitur</a></div><div className="mt-8 grid grid-cols-2 gap-3 text-[11px] font-bold text-[#36536F] sm:grid-cols-4 lg:grid-cols-2 xl:grid-cols-4">{["Siap Kerja","Siap Saing","Terhubung Pelatihan","Peluang Lebih Tepat"].map(item => <span key={item} className="flex items-center gap-2"><span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-[#DDEFFC] text-[#0B4EA2]"><Check size={12} strokeWidth={3} /></span>{item}</span>)}</div></div>
      <div className="relative min-h-[530px]"><div className="absolute left-4 top-16 hidden w-[280px] rounded-[24px] bg-[#061A33] p-5 text-white shadow-[0_30px_70px_rgba(6,26,51,.25)] sm:block"><div className="flex items-center justify-between"><div><p className="text-[9px] font-bold uppercase tracking-[.14em] text-[#7EBBFA]">Dashboard Pribadi</p><p className="mt-1 text-base font-bold">Career readiness</p></div><BarChart3 className="text-[#FFD23F]" size={21} /></div><p className="mt-5 text-4xl font-bold text-[#FFD23F]">72%</p><div className="mt-4 h-2 rounded-full bg-white/10"><div className="h-full w-[72%] rounded-full bg-[#2A8CFF]" /></div><div className="mt-5 grid grid-cols-2 gap-2">{[["Job match","92%"],["CV ready","78%"],["Pelatihan","6"],["Lamaran","8"]].map(([l,v]) => <div key={l} className="rounded-xl bg-white/[.07] p-3"><p className="text-[9px] text-[#9ABBDD]">{l}</p><p className="mt-1 text-sm font-bold">{v}</p></div>)}</div></div>
        <div className="absolute left-1/2 top-0 z-10 w-[250px] -translate-x-1/2 rounded-[36px] bg-[#07182D] p-2.5 shadow-[0_35px_90px_rgba(6,26,51,.32)]"><div className="overflow-hidden rounded-[29px] bg-white"><div className="flex justify-center bg-[#07182D] pb-2"><span className="h-5 w-24 rounded-b-xl bg-black" /></div><div className="p-4"><p className="text-[9px] font-bold text-[#0B4EA2]">Halo, Ilham 👋</p><h3 className="mt-1 text-base font-bold leading-5 text-[#061A33]">Siap jadi bagian dari generasi 2045?</h3><div className="mt-4 rounded-xl bg-[#EAF3FC] p-3"><div className="flex items-center gap-2"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#0B4EA2] text-[#FFD23F]"><BriefcaseBusiness size={15} /></span><div><p className="text-[9px] text-[#718298]">Rekomendasi untukmu</p><p className="text-[11px] font-bold text-[#061A33]">Junior Data Analyst</p></div></div><div className="mt-3 flex items-center justify-between"><span className="text-[9px] text-[#52667F]">Surabaya</span><span className="rounded-full bg-[#DDF7ED] px-2 py-1 text-[8px] font-bold text-[#087356]">92% cocok</span></div></div><p className="mt-4 text-[9px] font-bold uppercase tracking-[.1em] text-[#7A8A9D]">Mulai dari sini</p><div className="mt-3 grid grid-cols-4 gap-2">{[[Search,"Kerja"],[GraduationCap,"Latihan"],[MapPinned,"Peluang"],[FileUser,"CV"]].map(([Icon,l]) => { const C=Icon as typeof Search; return <div key={l as string} className="text-center"><span className="mx-auto flex h-9 w-9 items-center justify-center rounded-xl bg-[#F1F5F9] text-[#0B4EA2]"><C size={15} /></span><p className="mt-1 text-[7px] font-semibold text-[#52667F]">{l as string}</p></div>; })}</div><div className="mt-4 h-24 rounded-xl bg-[#061A33] p-3"><p className="text-[8px] text-[#93B9DF]">Peta peluang kerja</p><div className="mt-2 flex h-12 items-end gap-1">{[35,48,40,58,51,65,57].map((h,i)=><span key={i} className={`flex-1 rounded-t-sm ${i===5?"bg-[#FFD23F]":"bg-[#2A8CFF]"}`} style={{height:h}} />)}</div></div></div></div></div>
        <div className="absolute bottom-12 right-0 w-[300px] rounded-[24px] bg-white p-4 shadow-[0_24px_70px_rgba(6,26,51,.16)]"><div className="rounded-2xl bg-[#0B4EA2] p-4 text-white"><div className="flex items-center gap-3"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-[#FFD23F] text-[#061A33]"><BusFront size={25} /></span><div><p className="text-[9px] uppercase tracking-[.12em] text-[#BBD8F6]">Pelatihan keliling</p><p className="mt-1 text-base font-bold">BLK Mobile</p></div></div><div className="mt-4 flex items-center gap-2 text-[9px] font-semibold"><Navigation className="text-[#FFD23F]" size={13} />Surabaya → Sidoarjo → Gresik</div></div></div>
        {[["Cari Kerja Cerdas",5,2],["Pelatihan Terarah",78,7],["CV Digital",72,55]].map(([label,left,top])=><span key={label as string} className="absolute z-20 hidden rounded-xl bg-white px-3 py-2 text-[9px] font-bold text-[#16466F] shadow-[0_12px_30px_rgba(6,26,51,.12)] lg:block" style={{left:`${left}%`,top:`${top}%`}}>{label as string}</span>)}
      </div>
    </div></section>

    <section className="relative z-20 mx-auto -mt-12 max-w-[1320px] px-4 sm:px-6 lg:px-8"><div className="grid gap-3 rounded-[22px] bg-white p-3 shadow-[0_20px_55px_rgba(6,26,51,.12)] sm:grid-cols-2 lg:grid-cols-4">{[[BriefcaseBusiness,"Cari Kerja Cerdas","Lowongan dengan match score"],[BookOpenCheck,"Pelatihan Terarah","Online, hybrid, dan mobile"],[FileUser,"CV & Portofolio","Dokumen karier siap pakai"],[TrendingUp,"Progress Kesiapan","Targetmu selalu terukur"]].map(([Icon,title,copy]) => { const C=Icon as typeof BriefcaseBusiness; return <a key={title as string} href="#fitur" className="group flex min-h-[74px] items-center gap-3 rounded-2xl bg-[#F5F8FC] p-3 transition hover:bg-[#EAF3FC]"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-white text-[#0B4EA2] shadow-sm transition group-hover:bg-[#FFD23F] group-hover:text-[#061A33]"><C size={18} /></span><span><b className="block text-xs text-[#061A33]">{title as string}</b><small className="mt-1 block text-[10px] text-[#718298]">{copy as string}</small></span></a>; })}</div></section>

    <section id="masalah" className="scroll-mt-24 px-4 py-20 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-[1320px] gap-8 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#0B4EA2]">Masalah yang dibaca</p><h2 className="mt-3 text-3xl font-bold tracking-[-.035em] text-[#061A33] sm:text-4xl">Bonus demografi tidak cukup hanya dibaca dari jumlah tenaga kerja.</h2><p className="mt-4 text-sm leading-7 text-[#64788E]">Yang perlu dijembatani adalah jarak antara skill lulusan, kebutuhan industri, dan akses pelatihan yang berbeda di setiap wilayah.</p></div><div className="grid gap-3 sm:grid-cols-3">{[["01","Data belum menjadi arah","Informasi pendidikan dan industri perlu dibaca sebagai keputusan."],["02","Skill berbeda tiap wilayah","Kebutuhan Cilegon tidak sama dengan Garut atau Lombok Timur."],["03","Pelatihan perlu tepat sasaran","Program harus terhubung dengan peluang kerja dan kesiapan peserta."]].map(([number,title,copy]) => <article key={number} className="dashboard-card flex min-h-[190px] flex-col p-5"><span className="text-xs font-bold text-[#0B4EA2]">{number}</span><h3 className="mt-5 text-sm font-bold text-[#061A33]">{title}</h3><p className="mt-2 text-xs leading-5 text-[#667A90]">{copy}</p><span className="mt-auto h-1 w-10 rounded-full bg-[#FFD23F]" /></article>)}</div></div></section>

    <FeatureShowcase />

    <section id="cara-kerja" className="scroll-mt-24 bg-[#061A33] py-20 text-white"><div className="mx-auto max-w-[1440px] px-4 sm:px-6 lg:px-8"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#FFD23F]">Cara kerjanya</p><h2 className="mt-3 max-w-2xl text-3xl font-bold tracking-[-.035em] sm:text-4xl">Cara Network App Membantu Perjalanan Karirmu</h2><div className="mt-10 grid gap-3 md:grid-cols-2 lg:grid-cols-4">{steps.map((step,i)=><article key={step} className="relative rounded-2xl bg-white/[.065] p-5 shadow-[inset_0_1px_0_rgba(255,255,255,.08)]"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#FFD23F] text-sm font-bold text-[#061A33]">{i+1}</span><p className="mt-4 text-xs font-bold leading-5 text-white">{step}</p>{i<steps.length-1?<span className="absolute -right-2 top-8 z-10 hidden h-px w-4 bg-[#FFD23F]/70 lg:block" />:null}</article>)}</div></div></section>

    <section id="peta-peluang" className="mx-auto max-w-[1440px] scroll-mt-24 px-4 py-20 sm:px-6 lg:px-8"><div className="grid gap-8 lg:grid-cols-[1.35fr_.65fr]"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#0B4EA2]">Peta peluang nasional</p><h2 className="mt-3 text-3xl font-bold tracking-[-.035em] text-[#061A33] sm:text-4xl">Peta Peluang Kerja dan Pelatihan Nasional</h2><p className="mt-4 max-w-2xl text-sm leading-6 text-[#687B91]">Peta memakai geometri 38 provinsi Indonesia untuk menunjukkan risiko, lokasi BLK Mobile, dan kebutuhan pelatihan.</p><div className="mt-7"><IndonesiaMap /></div></div><div className="flex flex-col justify-end gap-3">{[["12","Wilayah prioritas tinggi"],["28","Pelatihan aktif"],["7","BLK Mobile terjadwal"],["Digital & manufaktur","Sektor paling dibutuhkan"]].map(([v,l],i)=><div key={l} className={`rounded-2xl p-5 ${i===0?"bg-[#FFD23F]":"bg-white shadow-[0_10px_32px_rgba(6,26,51,.07)]"}`}><p className={`text-xl font-bold ${i===0?"text-[#061A33]":"text-[#0B4EA2]"}`}>{v}</p><p className="mt-1 text-xs font-semibold text-[#52667F]">{l}</p></div>)}</div></div></section>

    <section id="blk-mobile" className="bg-[#EAF3FC] py-20"><div className="mx-auto grid max-w-[1440px] gap-10 px-4 sm:px-6 lg:grid-cols-[.8fr_1.2fr] lg:px-8"><div><span className="flex h-14 w-14 items-center justify-center rounded-2xl bg-[#FFD23F] text-[#061A33]"><BusFront size={28} /></span><h2 className="mt-5 text-3xl font-bold tracking-[-.035em] text-[#061A33] sm:text-4xl">BLK Mobile: Pelatihan Keliling Sampai ke Daerah</h2><p className="mt-4 text-sm leading-7 text-[#5F748B]">Ketika suatu wilayah terdeteksi memiliki kebutuhan pelatihan tinggi, BLK Mobile dapat diarahkan untuk membuka kelas sesuai kebutuhan lokal.</p><Link href="/dashboard/blk-mobile" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-[#061A33] px-5 py-3 text-xs font-bold text-white">Lihat jadwal BLK Mobile <ArrowRight size={15} /></Link></div><div className="rounded-[26px] bg-[#071E39] p-5 text-white shadow-[0_24px_70px_rgba(6,26,51,.2)]"><div className="grid gap-4 sm:grid-cols-[.9fr_1.1fr]"><div className="flex min-h-[230px] flex-col justify-between rounded-2xl bg-[#0B4EA2] p-5"><div className="flex items-center justify-between"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#BFD9F6]">BLK Mobile 03</p><BadgeCheck className="text-[#FFD23F]" size={20} /></div><div><BusFront className="text-[#FFD23F]" size={54} /><p className="mt-4 text-xl font-bold">Surabaya → Sidoarjo</p><p className="mt-2 text-xs text-[#C9DEF3]">Administrasi Digital · 40 peserta</p></div></div><div className="grid grid-cols-2 gap-3">{[[MapPinned,"Menjangkau daerah prioritas"],[Target,"Sesuai kebutuhan wilayah"],[BadgeCheck,"Sertifikasi kompetensi"],[Handshake,"Terhubung peluang kerja"]].map(([Icon,l])=>{const C=Icon as typeof Target;return <div key={l as string} className="rounded-2xl bg-white/[.07] p-4"><C className="text-[#FFD23F]" size={20} /><p className="mt-3 text-xs font-bold leading-5">{l as string}</p></div>})}</div></div></div></div></section>

    <section className="mx-auto max-w-[1440px] px-4 py-20 sm:px-6 lg:px-8"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div className="flex flex-col justify-center"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#0B4EA2]">Perkembangan diri</p><h2 className="mt-3 text-3xl font-bold tracking-[-.035em] text-[#061A33] sm:text-4xl">Pantau kesiapanmu sebelum masuk dunia kerja.</h2><p className="mt-4 text-sm leading-7 text-[#687B91]">Semakin banyak pelatihan, latihan interview, dan project yang kamu selesaikan, semakin tinggi kesiapanmu untuk melamar kerja.</p></div><div className="dashboard-card grid gap-5 p-5 sm:p-7 md:grid-cols-[.7fr_1.3fr]"><div className="flex flex-col justify-center rounded-2xl bg-[#061A33] p-6 text-white"><p className="text-xs text-[#9DC4EA]">Career Readiness Score</p><p className="mt-2 text-5xl font-bold text-[#FFD23F]">72%</p><p className="mt-4 text-xs leading-5 text-[#BED5EC]">Kamu cukup siap untuk posisi entry-level.</p></div><div className="space-y-4">{[["CV Readiness",78],["Portfolio Readiness",55],["Interview Readiness",64],["Job Match Score",81]].map(([l,v],i)=><div key={l as string}><div className="mb-2 flex justify-between text-xs"><span className="font-semibold text-[#52667F]">{l as string}</span><b>{v}%</b></div><div className="h-2 rounded-full bg-[#E8EDF3]"><div className={`h-full rounded-full ${i===1?"bg-[#FFD23F]":"bg-[#0B4EA2]"}`} style={{width:`${v}%`}} /></div></div>)}</div></div></div></section>

    <section className="px-4 pb-20 sm:px-6 lg:px-8"><div className="relative mx-auto max-w-[1408px] overflow-hidden rounded-[28px] bg-[#0B4EA2] px-6 py-12 text-center text-white shadow-[0_24px_70px_rgba(11,78,162,.24)] sm:px-10"><div className="absolute inset-0 nexwork-dot-map opacity-25" /><div className="relative"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#FFD23F]">Mulai dari langkah kecil</p><h2 className="mx-auto mt-3 max-w-2xl text-3xl font-bold tracking-[-.035em] sm:text-4xl">Siap bangun jalur karirmu mulai sekarang?</h2><p className="mx-auto mt-4 max-w-2xl text-sm leading-6 text-[#D4E5F7]">Coba demo Network App dan lihat bagaimana data, pelatihan, CV digital, dan peluang kerja terhubung dalam satu platform.</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/login" className="inline-flex min-h-12 items-center justify-center rounded-xl bg-[#FFD23F] px-5 text-sm font-bold text-[#061A33]">Masuk Demo</Link><Link href="/dashboard" className="inline-flex min-h-12 items-center justify-center rounded-xl bg-white/10 px-5 text-sm font-bold text-white">Lihat Dashboard</Link></div></div></div></section>

    <footer className="border-t border-[#DCE7F1] bg-white"><div className="mx-auto flex max-w-[1440px] flex-col gap-3 px-4 py-8 text-xs text-[#718298] sm:flex-row sm:items-center sm:justify-between sm:px-6 lg:px-8"><p><b className="text-[#061A33]">NexWork 2045</b> · Network App untuk generasi siap kerja.</p><p>Prototype berbasis data simulasi</p></div></footer>
  </main>;
}
