import { BusFront, CalendarDays, MapPin, Navigation, Route, Users } from "lucide-react";
import { blkMobileSummary, blkMobileUnits } from "@/src/data/blkMobile";
import { PageIntro, SectionCard, StatCard, StatusBadge, primaryButton } from "@/src/components/dashboard/ui-v2";

export function BlkMobileV2() { return <div className="space-y-5 sm:space-y-6"><PageIntro eyebrow="Pelatihan keliling" title="Akses skill praktis yang bergerak lebih dekat ke daerahmu" description="BLK Mobile menghubungkan kebutuhan industri lokal dengan pelatihan, sertifikasi, dan mitra kerja di wilayah prioritas." action={<button className={primaryButton}><Navigation size={15} /> Cari unit terdekat</button>} />
  <div className="grid auto-rows-fr gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard title="Unit terdekat" value="18 km" note={blkMobileSummary.nearest} icon={MapPin} tone="navy" /><StatCard title="Program tersedia" value={`${blkMobileSummary.openPrograms}`} note="Dapat dipilih pengguna demo." icon={BusFront} tone="amber" /><StatCard title="Kunjungan berikutnya" value="24 Agu" note="Area Surabaya dan Sidoarjo." icon={CalendarDays} tone="blue" /><StatCard title="Kapasitas tersisa" value="68" note="Gabungan unit aktif terdekat." icon={Users} tone="green" /></div>
  <div className="grid auto-rows-fr gap-4 lg:grid-cols-2">{blkMobileUnits.map(unit => <article key={unit.id} className="dashboard-card dashboard-card-hover flex h-full min-h-[280px] flex-col p-5 sm:p-6"><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><span className="flex h-12 w-12 items-center justify-center rounded-[15px] bg-[#061A33] text-[#FFD43B]"><BusFront size={23} /></span><div><p className="text-sm font-bold text-[#061A33]">{unit.id}</p><p className="mt-1 text-xs text-[#718298]">{unit.destination}</p></div></div><StatusBadge value={unit.status} /></div><h2 className="mt-5 text-base font-bold text-[#163553]">{unit.trainingType}</h2><div className="mt-4 grid grid-cols-2 gap-3">{[["Kapasitas",`${unit.capacity} peserta`],["Jadwal",unit.schedule],["Mitra lokal",unit.partner],["Rute",unit.route]].map(([l,v]) => <div key={l} className="rounded-xl bg-[#F3F6FA] p-3"><p className="text-[9px] font-bold uppercase tracking-[.08em] text-[#8795A6]">{l}</p><p className="mt-1.5 text-[11px] font-bold leading-4 text-[#324B65]">{v}</p></div>)}</div><button className={`${primaryButton} mt-auto w-full pt-2`}>Lihat program & rute</button></article>)}</div>
  <SectionCard title="Alur layanan BLK Mobile" description="Dari pemetaan risiko hingga pengguna siap terhubung dengan peluang kerja."><div className="grid gap-3 md:grid-cols-4">{[[MapPin,"Wilayah diprioritaskan"],[BusFront,"Unit dijadwalkan"],[Users,"Pelatihan & sertifikasi"],[Route,"Terhubung ke industri"]].map(([Icon,label],i) => { const C=Icon as typeof BusFront; return <div key={label as string} className="relative rounded-xl bg-[#F3F6FA] p-4 text-center"><span className="mx-auto flex h-10 w-10 items-center justify-center rounded-xl bg-white text-[#0B4EA2]"><C size={18} /></span><p className="mt-3 text-xs font-bold text-[#334C65]">{i+1}. {label as string}</p></div>; })}</div></SectionCard>
  </div>; }
