"use client";
import { useState } from "react";
import { BusFront, Filter, MapPinned, Target } from "lucide-react";
import { IndonesiaMap } from "@/src/components/dashboard/indonesia-map";
import { getProvinceInsight, mapStats } from "@/src/data/nationalMap";
import { PageIntro, SectionCard, StatCard, StatusBadge, primaryButton } from "@/src/components/dashboard/ui-v2";

export function NationalMapV2() {
  const [selected, setSelected] = useState("Jawa Timur");
  const [risk, setRisk] = useState("Semua risiko");
  const insight = getProvinceInsight(selected);
  return <div className="space-y-5 sm:space-y-6"><PageIntro eyebrow="Workforce intelligence nasional" title="Satu peta untuk membaca kebutuhan skill Indonesia" description="Peta ini memakai geometri batas 38 provinsi, bukan ilustrasi wilayah. Pilih provinsi untuk membaca risiko, kebutuhan pelatihan, dan status BLK Mobile." action={<button className={primaryButton}><Target size={15} /> Lihat wilayah prioritas</button>} />
    <div className="grid auto-rows-fr gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard title="Provinsi terpetakan" value={`${mapStats.provinces}`} note="Batas wilayah berbasis GeoJSON." icon={MapPinned} tone="blue" /><StatCard title="Wilayah prioritas" value={`${mapStats.priorityAreas}`} note="Memerlukan intervensi terarah." icon={Target} tone="red" /><StatCard title="Unit BLK Mobile" value={`${mapStats.mobileUnits}`} note="Aktif dan terjadwal nasional." icon={BusFront} tone="navy" /><StatCard title="Pelatihan aktif" value={`${mapStats.activeTrainings}`} note="Menjawab kebutuhan lokal." icon={Filter} tone="amber" /></div>
    <section className="dashboard-card p-4 sm:p-5"><div className="grid gap-3 md:grid-cols-3"><select value={selected} onChange={e => setSelected(e.target.value)} className="filter-control w-full" aria-label="Provinsi">{["Jawa Timur","Jawa Barat","Jawa Tengah","Banten","Sulawesi Selatan","Nusa Tenggara Barat","Papua","Bali","Kalimantan Timur"].map(x => <option key={x}>{x}</option>)}</select><select value={risk} onChange={e => setRisk(e.target.value)} className="filter-control w-full"><option>Semua risiko</option><option>Rendah</option><option>Sedang</option><option>Tinggi</option><option>Sangat Tinggi</option></select><select className="filter-control w-full" aria-label="Jenis pelatihan"><option>Semua jenis pelatihan</option><option>Data & Teknologi</option><option>Industri</option><option>Komunikasi & Karir</option></select></div></section>
    <div className="grid gap-5 xl:grid-cols-12"><section className="dashboard-card overflow-hidden p-4 sm:p-5 xl:col-span-8"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold text-[#061A33]">Peta prioritas nasional</h2><p className="mt-1 text-xs text-[#718298]">Pilih langsung provinsi pada peta untuk menampilkan detail.</p></div><div className="flex flex-wrap gap-2 text-[10px] font-bold">{[["bg-[#70C9F2]","Rendah"],["bg-[#F8D35B]","Sedang"],["bg-[#F2A53A]","Tinggi"],["bg-[#DF625A]","Sangat tinggi"]].map(([c,l]) => <span key={l} className="flex items-center gap-1.5 text-[#607289]"><i className={`h-2.5 w-2.5 rounded-sm ${c}`} />{l}</span>)}</div></div><IndonesiaMap selectedProvince={selected} onProvinceChange={setSelected} riskFilter={risk} /></section>
      <aside className="xl:col-span-4"><SectionCard title={selected} description="Detail wilayah terpilih" action={<StatusBadge value={insight.risk} />} className="h-full"><div className="grid grid-cols-2 gap-3">{[["Skor risiko",`${insight.score}/100`],["Mismatch index",insight.mismatch.toFixed(2)],["TPT vokasi",`${insight.tpt}%`],["BLK Mobile",insight.mobile]].map(([label,value]) => <div key={label} className="rounded-xl bg-[#F2F6FA] p-4"><p className="text-[10px] font-bold uppercase tracking-[.08em] text-[#8090A3]">{label}</p><p className="mt-2 text-sm font-bold text-[#061A33]">{value}</p></div>)}</div><div className="mt-4 rounded-xl bg-[#EAF3FC] p-4"><p className="text-[10px] font-bold uppercase tracking-[.1em] text-[#0B4EA2]">Pelatihan prioritas</p><p className="mt-2 text-sm font-bold leading-5 text-[#16395F]">{insight.training}</p></div><div className="mt-3 rounded-xl bg-[#F2F6FA] p-4"><p className="text-[10px] font-bold uppercase tracking-[.1em] text-[#63778E]">Sektor potensial</p><p className="mt-2 text-xs font-semibold leading-5 text-[#3A526B]">{insight.sector}</p></div><div className="mt-3 rounded-xl bg-[#FFF6D4] p-4"><p className="text-[10px] font-bold uppercase tracking-[.1em] text-[#775A00]">Rekomendasi aksi</p><p className="mt-2 text-xs leading-5 text-[#6B5A25]">{insight.action}</p></div></SectionCard></aside></div>
  </div>;
}
