import Link from "next/link";
import { ArrowRight, BookOpenCheck, BriefcaseBusiness, BusFront, Check, FileUser, MapPin, MessageCircleMore, TrendingUp, UserRound } from "lucide-react";
import { IndonesiaMap } from "@/src/components/dashboard/indonesia-map";
import { jobs } from "@/src/data/jobs";
import { trainings } from "@/src/data/trainings";
import { PageIntro, ProgressBar, SectionCard, StatCard, StatusBadge, primaryButton, secondaryButton } from "@/src/components/dashboard/ui-v2";

export function DashboardOverviewV3() {
  return <div className="space-y-5 sm:space-y-6"><PageIntro eyebrow="Ringkasan personal" title="Halo Ilham, langkah berikutnya sudah lebih jelas" description="Profil, pelatihan, CV, dan kebutuhan industri dibaca bersama agar rekomendasimu tidak berhenti sebagai daftar." action={<Link href="/dashboard/jobs" className={primaryButton}>Lihat peluang terbaik <ArrowRight size={15} /></Link>} />
    <div className="grid auto-rows-fr gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard title="Career Readiness Score" value="72%" note="Naik 5 poin dalam 30 hari." icon={TrendingUp} tone="navy" /><StatCard title="Job Match Tertinggi" value="92%" note="Junior Data Analyst, Surabaya." icon={BriefcaseBusiness} tone="green" /><StatCard title="Pelatihan Direkomendasikan" value="6" note="Tiga dapat dimulai minggu ini." icon={BookOpenCheck} tone="amber" /><StatCard title="BLK Mobile Terdekat" value="18 km" note="Empat program tersedia." icon={BusFront} tone="blue" /></div>
    <div className="grid gap-5 xl:grid-cols-12"><SectionCard className="xl:col-span-8" title="Peta peluang kerja nasional" description="Geometri 38 provinsi dengan kategori risiko dan titik BLK Mobile." action={<Link href="/dashboard/national-map" className="text-xs font-bold text-[#0B4EA2]">Buka peta →</Link>}><IndonesiaMap compact /></SectionCard><div className="space-y-5 xl:col-span-4"><section className="dashboard-card p-5"><div className="flex items-center gap-3"><span className="flex h-12 w-12 items-center justify-center rounded-[15px] bg-[#0B4EA2] text-sm font-bold text-white">IJ</span><div><p className="text-sm font-bold text-[#061A33]">Ilham Jaya</p><p className="mt-0.5 text-[10px] text-[#718298]">Fresh Graduate · Surabaya</p></div></div><div className="mt-5"><ProgressBar label="Kelengkapan profil" value={84} /></div><div className="mt-4 flex flex-wrap gap-2">{["Data Analyst","Digital Marketing","Web Developer"].map(x=><span key={x} className="rounded-full bg-[#EAF3FC] px-2.5 py-1 text-[10px] font-bold text-[#24517E]">{x}</span>)}</div><Link href="/dashboard/profile" className={`${secondaryButton} mt-5 w-full`}>Lihat profil</Link></section><section className="dashboard-card p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-bold text-[#061A33]">Progress kesiapan kerja</p><p className="mt-1 text-[10px] text-[#718298]">Fokus pada portofolio dan interview.</p></div><span className="text-2xl font-bold text-[#0B4EA2]">72%</span></div><div className="mt-4 space-y-3"><ProgressBar label="CV" value={78} /><ProgressBar label="Portofolio" value={55} tone="yellow" /><ProgressBar label="Interview" value={64} /></div></section></div></div>
    <div className="grid auto-rows-fr gap-5 lg:grid-cols-3"><SectionCard title="Rekomendasi pekerjaan" description="Berdasarkan skill dan domisili."><div className="space-y-3">{jobs.slice(0,3).map(job=><div key={job.id} className="rounded-xl bg-[#F2F6FA] p-3"><div className="flex items-start justify-between gap-2"><div><p className="text-xs font-bold text-[#183653]">{job.title}</p><p className="mt-1 flex items-center gap-1 text-[10px] text-[#718298]"><MapPin size={11} />{job.location}</p></div><StatusBadge value={`${job.match}%`} /></div></div>)}</div><Link href="/dashboard/jobs" className={`${secondaryButton} mt-5 w-full`}>Lihat semua pekerjaan</Link></SectionCard>
      <SectionCard title="Pelatihan untukmu" description="Skill yang paling dekat dengan target kerja."><div className="space-y-3">{trainings.slice(0,3).map(item=><div key={item.id} className="flex items-center gap-3 rounded-xl bg-[#F2F6FA] p-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-white text-[#0B4EA2]"><BookOpenCheck size={16} /></span><div className="min-w-0"><p className="truncate text-xs font-bold text-[#183653]">{item.name}</p><p className="mt-1 text-[10px] text-[#718298]">{item.mode} · {item.duration}</p></div></div>)}</div><Link href="/dashboard/training" className={`${secondaryButton} mt-5 w-full`}>Buka katalog pelatihan</Link></SectionCard>
      <SectionCard title="CV & Portofolio" description="Empat dari enam bagian sudah siap."><div className="rounded-2xl bg-[#061A33] p-5 text-white"><p className="text-[10px] font-bold uppercase tracking-[.1em] text-[#94BDE5]">CV Readiness</p><p className="mt-2 text-4xl font-bold text-[#FFD23F]">78%</p><div className="mt-4 h-2 rounded-full bg-white/10"><div className="h-full w-[78%] rounded-full bg-[#2A8CFF]" /></div></div><div className="mt-4 space-y-2">{["Profil lengkap","Skill terisi","Sertifikat terhubung"].map(x=><p key={x} className="flex items-center gap-2 text-[11px] font-semibold text-[#52667F]"><span className="flex h-5 w-5 items-center justify-center rounded-full bg-[#E4F8F0] text-[#087356]"><Check size={11} /></span>{x}</p>)}</div><Link href="/dashboard/cv-portfolio" className={`${primaryButton} mt-5 w-full`}><FileUser size={14} /> Perkuat portofolio</Link></SectionCard></div>
  </div>;
}
