"use client";
import { useMemo, useState } from "react";
import { ArrowRight, GraduationCap, Search } from "lucide-react";
import { trainingCategories, trainings } from "@/src/data/trainings";
import { PageIntro, StatusBadge, primaryButton, secondaryButton } from "@/src/components/dashboard/ui-v2";

export function TrainingCatalog() {
  const [category, setCategory] = useState("Semua pelatihan"); const [query, setQuery] = useState("");
  const visible = useMemo(() => trainings.filter(item => (category === "Semua pelatihan" || (category === "BLK Mobile" ? item.mode === "BLK Mobile" : item.category === category)) && item.name.toLowerCase().includes(query.toLowerCase())), [category, query]);
  return <div className="space-y-5 sm:space-y-6"><PageIntro eyebrow="Katalog keterampilan" title="Belajar hal yang benar, pada waktu yang tepat" description="Pilih kelas berdasarkan pekerjaan tujuanmu. Setiap pelatihan menjelaskan skill yang akan dibawa pulang, bukan hanya daftar materi." action={<button className={primaryButton}>Lihat rekomendasi saya <ArrowRight size={15} /></button>} />
    <section className="dashboard-card p-4 sm:p-5"><div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div className="flex max-w-full gap-2 overflow-x-auto pb-1">{trainingCategories.map(item => <button key={item} onClick={() => setCategory(item)} className={`min-h-9 shrink-0 rounded-xl px-3.5 text-[11px] font-bold transition ${category === item ? "bg-[#061A33] text-white" : "bg-[#F0F4F8] text-[#5E7188] hover:bg-[#E5EDF5]"}`}>{item}</button>)}</div><label className="relative block w-full xl:w-64"><Search className="pointer-events-none absolute left-3.5 top-1/2 z-10 -translate-y-1/2 text-[#7D8EA2]" size={15} aria-hidden="true" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Cari pelatihan" className="filter-control filter-control-with-icon w-full" /></label></div></section>
    <div className="grid auto-rows-fr gap-4 md:grid-cols-2 2xl:grid-cols-3">{visible.map((item, index) => <article key={item.id} className="dashboard-card dashboard-card-hover flex h-full min-h-[286px] flex-col overflow-hidden"><div className={`h-1.5 shrink-0 ${index % 3 === 0 ? "bg-[#0B4EA2]" : index % 3 === 1 ? "bg-[#FFD43B]" : "bg-[#19A77B]"}`} /><div className="flex flex-1 flex-col p-4 sm:p-5"><div className="flex items-start justify-between gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#EAF3FC] text-[#0B4EA2]"><GraduationCap size={18} /></span><StatusBadge value={item.status} /></div><p className="mt-3 text-[9px] font-bold uppercase tracking-[.12em] text-[#0B4EA2]">{item.category}</p><h2 className="mt-1.5 min-h-10 text-base font-bold leading-5 text-[#061A33]">{item.name}</h2><div className="mt-3 grid grid-cols-3 gap-2 rounded-xl bg-[#F3F6FA] px-3 py-2.5 text-center"><div><p className="text-[8px] uppercase text-[#8291A3]">Level</p><p className="mt-0.5 text-[10px] font-bold text-[#344B64]">{item.level}</p></div><div><p className="text-[8px] uppercase text-[#8291A3]">Durasi</p><p className="mt-0.5 text-[10px] font-bold text-[#344B64]">{item.duration}</p></div><div><p className="text-[8px] uppercase text-[#8291A3]">Mode</p><p className="mt-0.5 text-[10px] font-bold text-[#344B64]">{item.mode}</p></div></div><div className="mt-3 flex min-h-6 flex-wrap content-start gap-1.5">{item.skills.map(skill => <span key={skill} className="rounded-full bg-[#FFF6D2] px-2.5 py-1 text-[9px] font-bold leading-4 text-[#715600]">{skill}</span>)}</div><button className={`${item.status === "Tersedia" ? primaryButton : secondaryButton} mt-3 w-full`}>{item.status === "Tersedia" ? "Ikuti pelatihan" : "Lihat detail"}</button></div></article>)}</div>
  </div>;
}
