"use client";
import { useMemo, useState } from "react";
import { BusFront, Filter, MapPinned, Target } from "lucide-react";
import { mapStats, nationalRegions } from "@/src/data/nationalMap";
import { PageIntro, SectionCard, StatCard, StatusBadge, primaryButton } from "@/src/components/dashboard/ui-v2";
import { NationalMapV2 } from "@/src/components/dashboard/national-map-v2";

export default function NationalMapPage() {
  return <NationalMapV2 />;
  /* Previous abstract map retained below temporarily.
  const [selectedId, setSelectedId] = useState("java"); const [risk, setRisk] = useState("Semua risiko");
  const selected = nationalRegions.find(x => x.id === selectedId) ?? nationalRegions[1];
  const visible = useMemo(() => nationalRegions.filter(x => risk === "Semua risiko" || x.risk === risk), [risk]);
  const riskColor = (value: string) => value === "Sangat Tinggi" ? "bg-[#E7685D] text-white" : value === "Tinggi" ? "bg-[#F2A733] text-[#382500]" : value === "Sedang" ? "bg-[#FFD95E] text-[#4A3900]" : "bg-[#70C9F2] text-[#06355A]";
  return <div className="space-y-5 sm:space-y-6"><PageIntro eyebrow="Workforce intelligence nasional" title="Satu peta untuk membaca kebutuhan skill Indonesia" description="Lihat risiko wilayah, titik BLK Mobile, dan program prioritas tanpa kehilangan konteks kebutuhan pengguna di tiap daerah." action={<button className={primaryButton}><Target size={15} /> Lihat wilayah prioritas</button>} />
    <div className="grid auto-rows-fr gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard title="Provinsi terpetakan" value={`${mapStats.provinces}`} note="Cakupan visualisasi nasional." icon={MapPinned} tone="blue" /><StatCard title="Wilayah prioritas" value={`${mapStats.priorityAreas}`} note="Memerlukan intervensi terarah." icon={Target} tone="red" /><StatCard title="Unit BLK Mobile" value={`${mapStats.mobileUnits}`} note="Aktif dan terjadwal nasional." icon={BusFront} tone="navy" /><StatCard title="Pelatihan aktif" value={`${mapStats.activeTrainings}`} note="Menjawab kebutuhan lokal." icon={Filter} tone="amber" /></div>
    <section className="dashboard-card p-4 sm:p-5"><div className="grid gap-3 md:grid-cols-3"><select className="filter-control w-full" aria-label="Provinsi"><option>Semua provinsi</option>{nationalRegions.map(x => <option key={x.id}>{x.province}</option>)}</select><select value={risk} onChange={e => setRisk(e.target.value)} className="filter-control w-full"><option>Semua risiko</option><option>Rendah</option><option>Sedang</option><option>Tinggi</option><option>Sangat Tinggi</option></select><select className="filter-control w-full" aria-label="Jenis pelatihan"><option>Semua jenis pelatihan</option><option>Data & Teknologi</option><option>Industri</option><option>Komunikasi & Karir</option></select></div></section>
    <div className="grid gap-5 xl:grid-cols-12"><section className="dashboard-card overflow-hidden xl:col-span-8"><div className="flex flex-wrap items-center justify-between gap-3 px-5 pb-2 pt-5"><div><h2 className="text-lg font-bold text-[#061A33]">Peta prioritas nasional</h2><p className="mt-1 text-xs text-[#718298]">Pilih kawasan untuk melihat data dan rekomendasi.</p></div><div className="flex flex-wrap gap-2 text-[10px] font-bold">{[["bg-[#70C9F2]","Rendah"],["bg-[#FFD95E]","Sedang"],["bg-[#F2A733]","Tinggi"],["bg-[#E7685D]","Sangat tinggi"]].map(([c,l]) => <span key={l} className="flex items-center gap-1.5 text-[#607289]"><i className={`h-2.5 w-2.5 rounded-full ${c}`} />{l}</span>)}</div></div>
      <div className="relative mx-4 mb-4 mt-2 h-[460px] overflow-hidden rounded-2xl bg-[#071E39] nexwork-dot-map sm:mx-5 sm:mb-5"><div className="absolute left-5 top-5 z-10 rounded-xl bg-white/[0.08] px-3 py-2 backdrop-blur"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#85BDF7]">Indonesia</p><p className="mt-1 text-xs font-semibold text-white">38 provinsi · 7 kawasan utama</p></div>{visible.map(region => <button key={region.id} onClick={() => setSelectedId(region.id)} className={`absolute flex min-h-10 items-center justify-center rounded-full px-3 text-[10px] font-bold shadow-[0_10px_20px_rgba(0,0,0,.25)] transition hover:scale-105 ${riskColor(region.risk)} ${selectedId === region.id ? "ring-4 ring-white/25" : ""}`} style={{ left: `${region.x}%`, top: `${region.y}%`, width: `${Math.max(region.w, 11)}%`, transform: `rotate(${region.r}deg)` }}><span style={{ transform: `rotate(${-region.r}deg)` }}>{region.name}</span></button>)}
      {[{x:39,y:65},{x:59,y:60},{x:71,y:41},{x:91,y:38}].map((p,i)=><span key={i} className="absolute h-3 w-3 rounded-full bg-[#FFD43B] shadow-[0_0_0_5px_rgba(255,212,59,.18)]" style={{left:`${p.x}%`,top:`${p.y}%`}} title="Titik BLK Mobile" />)}</div></section>
      <aside className="xl:col-span-4"><SectionCard title={selected.name} description={selected.province} action={<StatusBadge value={selected.risk} />} className="h-full"><div className="grid grid-cols-2 gap-3">{[["Skor risiko",`${selected.score}/100`],["Mismatch index",selected.mismatch.toFixed(2)],["TPT vokasi",`${selected.tpt}%`],["BLK Mobile",selected.mobile]].map(([label,value]) => <div key={label} className="rounded-xl bg-[#F2F6FA] p-4"><p className="text-[10px] font-bold uppercase tracking-[.08em] text-[#8090A3]">{label}</p><p className="mt-2 text-sm font-bold text-[#061A33]">{value}</p></div>)}</div><div className="mt-4 rounded-xl bg-[#EAF3FC] p-4"><p className="text-[10px] font-bold uppercase tracking-[.1em] text-[#0B4EA2]">Pelatihan prioritas</p><p className="mt-2 text-sm font-bold text-[#16395F]">{selected.training}</p></div><div className="mt-4 rounded-xl bg-[#FFF6D4] p-4"><p className="text-[10px] font-bold uppercase tracking-[.1em] text-[#775A00]">Rekomendasi aksi</p><p className="mt-2 text-xs leading-5 text-[#6B5A25]">Buka kelas singkat bersama mitra industri lokal dan arahkan BLK Mobile ke kabupaten dengan akses pelatihan terendah.</p></div><button className={`${primaryButton} mt-5 w-full`}>Lihat rincian wilayah</button></SectionCard></aside></div>
  </div>;
  */
}
