"use client";
import { useMemo, useState } from "react";
import { Bookmark, BriefcaseBusiness, FileUser, MapPin, Search, SlidersHorizontal } from "lucide-react";
import { jobFilters, jobs } from "@/src/data/jobs";
import { PageIntro, StatusBadge, primaryButton, secondaryButton } from "@/src/components/dashboard/ui-v2";

export default function JobsPage() {
  const [query, setQuery] = useState(""); const [field, setField] = useState("Semua bidang"); const [location, setLocation] = useState("Semua lokasi"); const [saved, setSaved] = useState<number[]>([]);
  const visible = useMemo(() => jobs.filter(job => (job.title + job.company + job.skills.join(" ")).toLowerCase().includes(query.toLowerCase()) && (field === "Semua bidang" || job.field === field) && (location === "Semua lokasi" || job.location === location)), [query, field, location]);
  return <div className="space-y-5 sm:space-y-6">
    <PageIntro eyebrow="Rekomendasi untuk Ilham" title="Lowongan yang masuk akal untuk langkahmu sekarang" description="Kami mencocokkan skill, minat, domisili, dan pelatihanmu dengan kebutuhan industri di Jawa Timur." action={<div className="rounded-xl bg-white/10 px-4 py-3 text-right"><p className="text-[10px] text-[#BFD8FA]">Match tertinggi</p><p className="text-xl font-bold text-[#FFD43B]">92%</p></div>} />
    <section className="dashboard-card p-4 sm:p-5"><div className="grid gap-3 lg:grid-cols-[minmax(260px,1.4fr)_repeat(3,minmax(140px,.6fr))]"><label className="relative block"><Search className="pointer-events-none absolute left-3.5 top-1/2 z-10 -translate-y-1/2 text-[#7B8DA2]" size={17} aria-hidden="true" /><input value={query} onChange={e => setQuery(e.target.value)} className="filter-control filter-control-with-icon w-full" placeholder="Cari posisi, perusahaan, atau skill" /></label><select value={field} onChange={e => setField(e.target.value)} className="filter-control w-full">{jobFilters.fields.map(x => <option key={x}>{x}</option>)}</select><select value={location} onChange={e => setLocation(e.target.value)} className="filter-control w-full">{jobFilters.locations.map(x => <option key={x}>{x}</option>)}</select><select className="filter-control w-full" aria-label="Tipe kerja">{jobFilters.types.map(x => <option key={x}>{x}</option>)}</select></div><div className="mt-3 flex items-center justify-between text-[11px] text-[#718298]"><span>{visible.length} rekomendasi ditemukan</span><span className="flex items-center gap-1.5 font-semibold"><SlidersHorizontal size={13} /> Diurutkan dari match tertinggi</span></div></section>
    <div className="grid auto-rows-fr gap-4 lg:grid-cols-2 2xl:grid-cols-3">{visible.map(job => <article key={job.id} className="dashboard-card dashboard-card-hover flex h-full min-h-[320px] flex-col p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><span className="flex h-12 w-12 items-center justify-center rounded-[15px] bg-[#071E39] text-[#FFD43B]"><BriefcaseBusiness size={22} /></span><div className="flex items-center gap-2"><StatusBadge value={`${job.match}% cocok`} /><button onClick={() => setSaved(current => current.includes(job.id) ? current.filter(id => id !== job.id) : [...current, job.id])} aria-label="Simpan lowongan" className={`flex h-8 w-8 items-center justify-center rounded-lg ${saved.includes(job.id) ? "bg-[#FFF3C4] text-[#8A6600]" : "bg-[#F1F5F9] text-[#718298]"}`}><Bookmark size={15} fill={saved.includes(job.id) ? "currentColor" : "none"} /></button></div></div><h2 className="mt-5 text-lg font-bold tracking-[-.02em] text-[#061A33]">{job.title}</h2><p className="mt-1 text-xs font-semibold text-[#536981]">{job.company}</p><div className="mt-3 flex flex-wrap gap-x-4 gap-y-2 text-[11px] text-[#718298]"><span className="flex items-center gap-1.5"><MapPin size={13} />{job.location}</span><span>{job.type}</span><span>{job.salary}</span></div><div className="mt-4 rounded-xl bg-[#F2F7FC] p-3"><p className="text-[10px] font-bold uppercase tracking-[.1em] text-[#0B4EA2]">Mengapa direkomendasikan</p><p className="mt-1.5 text-xs leading-5 text-[#536981]">{job.reason}</p></div><div className="mt-4 flex flex-wrap gap-2">{job.skills.map(skill => <span key={skill} className="rounded-full bg-[#EEF2F6] px-2.5 py-1 text-[10px] font-bold text-[#53657A]">{skill}</span>)}</div><div className="mt-auto grid grid-cols-2 gap-2 pt-5"><button className={secondaryButton}>Lihat detail</button><button className={primaryButton}><FileUser size={14} /> Siapkan CV</button></div></article>)}</div>
  </div>;
}
