"use client";
import { useState } from "react";
import { CalendarCheck, Clock3, History, MessageCircleMore, Sparkles, UserRoundCheck } from "lucide-react";
import { consultationHistory, consultationSchedule, consultationTopics } from "@/src/data/consultations";
import { PageIntro, SectionCard, StatusBadge, primaryButton, secondaryButton } from "@/src/components/dashboard/ui-v2";

export default function CareerConsultationPage() {
  const [booked, setBooked] = useState<number[]>([]);
  return <div className="space-y-5 sm:space-y-6"><PageIntro eyebrow="Arah karier personal" title="Kadang yang dibutuhkan bukan kelas baru, tetapi percakapan yang tepat" description="Diskusikan CV, interview, jalur karier, atau strategi mencari kerja dengan mentor yang memahami level awal karier." action={<button className={primaryButton}><CalendarCheck size={15} /> Lihat semua jadwal</button>} />
    <section className="dashboard-card overflow-hidden"><div className="grid lg:grid-cols-[1fr_auto]"><div className="p-5 sm:p-6"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#FFF3C4] text-[#765A00]"><Sparkles size={18} /></span><div><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#0B4EA2]">Insight untukmu</p><h2 className="mt-1 text-base font-bold text-[#061A33]">Mulai dari Review CV dan Persiapan Interview</h2></div></div><p className="mt-3 max-w-3xl text-xs leading-5 text-[#62758B]">Kedua sesi ini paling relevan karena CV-mu sudah 78% lengkap dan job match tertinggimu sudah di atas 90%.</p></div><div className="flex min-w-[230px] items-center justify-center bg-[#071E39] p-5 text-white"><div><p className="text-[10px] text-[#98BDE3]">Slot tersedia minggu ini</p><p className="mt-1 text-3xl font-bold text-[#FFD43B]">12 sesi</p></div></div></div></section>
    <div className="grid auto-rows-fr gap-4 md:grid-cols-2 2xl:grid-cols-4">{consultationTopics.map(item => <article key={item.id} className="dashboard-card dashboard-card-hover flex min-h-[280px] flex-col p-5"><div className="flex items-start justify-between"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#EAF3FC] text-[#0B4EA2]"><MessageCircleMore size={20} /></span><StatusBadge value={booked.includes(item.id) ? "Dijadwalkan" : item.status} /></div><h2 className="mt-5 text-base font-bold text-[#061A33]">{item.title}</h2><p className="mt-2 text-xs leading-5 text-[#718298]">{item.description}</p><div className="mt-4 flex items-center justify-between text-[11px] text-[#52667F]"><span className="flex items-center gap-1.5"><Clock3 size={13} />{item.duration}</span><span className="font-semibold">{item.mentor}</span></div><button onClick={() => setBooked(ids => ids.includes(item.id) ? ids : [...ids,item.id])} className={`${booked.includes(item.id) ? secondaryButton : primaryButton} mt-auto w-full`}>{booked.includes(item.id) ? "Sudah dijadwalkan" : "Jadwalkan"}</button></article>)}</div>
    <div className="grid gap-5 xl:grid-cols-12"><SectionCard className="xl:col-span-7" title="Jadwal konsultasi tersedia" description="Pilih waktu yang tidak bertabrakan dengan agenda pelatihanmu."><div className="space-y-3">{consultationSchedule.map(item => <div key={item.date+item.time} className="flex flex-col gap-3 rounded-xl bg-[#F3F6FA] p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><span className="flex h-11 w-11 shrink-0 flex-col items-center justify-center rounded-xl bg-white text-[#0B4EA2] shadow-sm"><b className="text-xs">{item.date.split(" ")[0]}</b><small className="text-[9px]">{item.date.split(" ")[1]}</small></span><div><p className="text-xs font-bold text-[#183653]">{item.topic}</p><p className="mt-1 text-[10px] text-[#718298]">{item.time} · {item.mentor}</p></div></div><button className={secondaryButton}>Pilih jadwal</button></div>)}</div></SectionCard><SectionCard className="xl:col-span-5" title="Riwayat konsultasi" description="Catatan singkat agar progresmu tetap tersambung."><div className="space-y-4">{consultationHistory.map(item => <div key={item.date} className="flex gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-[#EAF3FC] text-[#0B4EA2]"><History size={16} /></span><div><p className="text-xs font-bold text-[#183653]">{item.topic}</p><p className="mt-1 text-[10px] text-[#718298]">{item.date} · {item.mentor}</p><p className="mt-1.5 text-[11px] leading-4 text-[#536981]">{item.note}</p></div></div>)}</div></SectionCard></div>
  </div>;
}
