import { Check, Download, ExternalLink, FileText, FolderKanban, Pencil, Plus, Sparkles } from "lucide-react";
import { cvChecklist, cvPortfolio } from "@/src/data/cvPortfolio";
import { PageIntro, ProgressBar, SectionCard, StatusBadge, primaryButton, secondaryButton } from "@/src/components/dashboard/ui-v2";

export default function CvPortfolioPage() { return <div className="space-y-5 sm:space-y-6"><PageIntro eyebrow="Dokumen karier" title="CV yang rapi, portofolio yang menunjukkan caramu bekerja" description="Susun bukti kemampuan dalam satu profil yang siap dibagikan saat menemukan lowongan yang tepat." action={<button className={primaryButton}><Plus size={15} /> Buat CV</button>} />
  <div className="grid gap-5 xl:grid-cols-12"><SectionCard className="xl:col-span-4" title="CV Readiness Score" description="Empat dari enam bagian sudah siap."><div className="flex items-end gap-2"><p className="text-5xl font-bold tracking-[-.06em] text-[#061A33]">{cvPortfolio.readiness}%</p><span className="mb-1 rounded-full bg-[#E4F8F0] px-2 py-1 text-[10px] font-bold text-[#087356]">+8 bulan ini</span></div><div className="mt-5"><ProgressBar value={cvPortfolio.readiness} tone="yellow" /></div><div className="mt-5 space-y-3">{cvChecklist.map(item => <div key={item.label} className="flex items-center gap-3"><span className={`flex h-6 w-6 items-center justify-center rounded-full ${item.done ? "bg-[#17A77B] text-white" : "bg-[#E8EDF3] text-[#9AA8B7]"}`}>{item.done ? <Check size={13} /> : null}</span><span className={`text-xs ${item.done ? "text-[#52657A]" : "font-semibold text-[#2F455E]"}`}>{item.label}</span></div>)}</div><div className="mt-5 rounded-xl bg-[#FFF6D4] p-4"><p className="text-xs font-bold text-[#6B5100]">Rekomendasi berikutnya</p><p className="mt-1.5 text-xs leading-5 text-[#745F26]">Tambahkan minimal 2 project agar portofoliomu lebih kuat.</p></div></SectionCard>
  <SectionCard className="xl:col-span-8" title="Preview CV" description="Tampilan simulasi satu halaman yang siap disesuaikan untuk setiap lowongan." action={<button className={secondaryButton}><Pencil size={14} /> Edit</button>}><div className="mx-auto max-w-[760px] rounded-2xl bg-[#F7F9FC] p-3 sm:p-5"><div className="overflow-hidden rounded-xl bg-white shadow-[0_14px_40px_rgba(6,26,51,.1)]"><div className="bg-[#061A33] p-6 text-white"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-2xl font-bold">Ilham Jaya</p><p className="mt-1 text-sm text-[#A9C9EA]">Junior Data Analyst · Digital Marketing</p></div><p className="text-xs text-[#FFD43B]">Surabaya, Jawa Timur</p></div></div><div className="grid gap-6 p-6 sm:grid-cols-[1.4fr_.6fr]"><div><CvBlock title="Ringkasan" text={cvPortfolio.summary} /><CvBlock title="Pengalaman" text={cvPortfolio.experience} /><CvBlock title="Pendidikan" text={cvPortfolio.education} /></div><div><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#0B4EA2]">Skill utama</p><div className="mt-3 flex flex-wrap gap-2">{cvPortfolio.skills.map(x => <span key={x} className="rounded-full bg-[#EAF3FC] px-2.5 py-1 text-[10px] font-bold text-[#24517E]">{x}</span>)}</div><p className="mt-6 text-[10px] font-bold uppercase tracking-[.12em] text-[#0B4EA2]">Sertifikat</p>{cvPortfolio.certificates.map(x => <p key={x} className="mt-2 text-[10px] leading-4 text-[#52667F]">• {x}</p>)}</div></div></div></div><div className="mt-5 grid gap-2 sm:grid-cols-3"><button className={secondaryButton}><FileText size={14} /> Preview CV</button><button className={secondaryButton}><FolderKanban size={14} /> Update Portofolio</button><button className={primaryButton}><Download size={14} /> Unduh simulasi</button></div></SectionCard></div>
  <SectionCard title="Project & portofolio" description={`Tautan publik: ${cvPortfolio.portfolioLink}`} action={<button className={secondaryButton}><ExternalLink size={14} /> Lihat profil</button>}><div className="grid gap-4 md:grid-cols-2">{cvPortfolio.projects.map(project => <article key={project.title} className="rounded-2xl bg-[#F1F6FB] p-5"><div className="flex items-start justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-white text-[#0B4EA2]"><Sparkles size={18} /></span><StatusBadge value={project.status} /></div><p className="mt-4 text-sm font-bold text-[#061A33]">{project.title}</p><p className="mt-1 text-xs text-[#718298]">{project.type} · Studi kasus personal</p></article>)}</div></SectionCard>
  </div>; }
function CvBlock({ title, text }: { title: string; text: string }) { return <div className="mb-5"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#0B4EA2]">{title}</p><p className="mt-2 text-[11px] leading-5 text-[#52667F]">{text}</p></div>; }
